services:
  postgres:
    image: postgres:16-alpine
    container_name: order-api-postgres
    environment:
      POSTGRES_DB: order_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - order-api-pgdata:/var/lib/postgresql/data

volumes:
  order-api-pgdata:
